# docker compose -p node-compiler -f compose.yaml up -d --remove-orphans --build
# docker compose -p node-compiler down
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# rollback_config, restart_policy
# for custom image
version: "3.8"

services:
  node-compiler:
    image: node:12
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    hostname: node-compiler
    container_name: node-compiler
    user: node
    working_dir: /opt/make/workspace
    tty: true
    volumes:
      - /opt/make/workspace:/opt/make/workspace
      - /opt/make/compilers:/opt/make/compilers
    environment:
      TZ: "Asia/Shanghai"
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${cpus:-2}"
          memory: ${memory:-2048M}
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s