# docker compose -p cicd-git -f compose.yaml up -d --remove-orphans --build
# docker compose -p cicd-git down
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# rollback_config, restart_policy
# for custom image
version: "3.8"

services:
  cicd-git:
    image: cicd/local/git:latest
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: git-docker-cli
    container_name: git-docker-cli
    working_dir: /opt/make/workspace
    # grep docker /etc/group 
    # `groupmod -g 2377 docker` systemctl restart docker.socket 
    user: 1000:${dockergid:-1000} # userId:groupid(docker-group-id)
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/make/workspace:/opt/make/workspace
      - /opt/make/compilers:/opt/make/compilers
    environment:
      TZ: "Asia/Shanghai"
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${cpus:-1}"
          memory: ${memory:-1024M}
