# docker compose -p host-etcd -f compose.yaml up -d
# docker compose -p host-etcd down
# need compose.v2 https://github.com/docker/compose
version: "3.8"
services:
  etcd-gateway:
    #image: softlang/etcd:v3.5.4
    image: softlang/etcd:v3.4.21
    #image: softlang/etcd:v3.3.27
    hostname: etcd4gateway
    container_name: etcd4gateway
    entrypoint: /usr/local/bin/etcd
    command: grpc-proxy start --endpoints=10.8.8.18:2378 --listen-addr=0.0.0.0:2376 --namespace=/my-key-namespace
    network_mode: host
    environment:
      ETCDCTL_API: 3
      TZ: "Asia/Shanghai"
      #etcget: "etcdctl --user=dev:dev get --prefix"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M