# docker-compose -p host-mvn -f compose.yaml up -d
# docker-compose -p host-mvn down
version: "3.8"

services:
  maven-reposilite:
    image: softlang/maven:reposilite-2.9.26
    hostname: maven-reposilite.dev
    container_name: maven-reposilite.dev
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx128M -Dreposilite.port=9083
      #- REPOSILITE_OPTS=${REPOSILITE_COMPOSE_OPTS}
    volumes:
      - ./data:/app/data
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

#PORT=8080
#MEMORY=128M
#JAVA_COMPOSE_OPTS=
#REPOSILITE_COMPOSE_OPTS=