# docker compose -p java-compiler -f compose.yaml up -d --remove-orphans --build
# docker compose -p java-compiler down
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# rollback_config, restart_policy
version: "3.8"

services:
  java-compiler:
    image: cicd/local/maven3-openjdk8:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: java-compiler
    container_name: java-compiler
    working_dir: /opt/make/workspace
    command: /bin/bash
    tty: true
    user: dev
    volumes:
      - /opt/make/workspace:/opt/make/workspace
      #- ./zyb_settings.xml:/home/dev/m2_settings.xml
    environment:
      TZ: "Asia/Shanghai"
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${cpus:-1}"
          memory: ${memory:-2048M}

