# docker compose -p golang-compiler -f compose.yaml up --build --remove-orphans -d
# docker compose -p golang-compiler down
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# rollback_config, restart_policy
# for custom image
version: "3.8"

services:
  golang-compiler:
    image: golang:1.17-alpine
    build:
      context: .
      dockerfile: Dockerfile
    hostname: golang-compiler
    container_name: golang-compiler
    working_dir: /opt/make/workspace
    tty: true
    volumes:
      - /opt/make/workspace:/opt/make/workspace
    environment:
      TZ: "Asia/Shanghai"
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
