# docker compose -p cicd-git -f compose.yaml up --build --remove-orphans -d
# docker compose -p cicd-git down
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# rollback_config, restart_policy
# for custom image
version: "3.8"

services:
  cicd-git:
    image: cicd/local/git:latest
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: git-clone-branch
    container_name: git-clone-branch
    working_dir: /opt/make/workspace
    user: git
    tty: true
    volumes:
      - /opt/make/workspace:/opt/make/workspace
    environment:
      TZ: "Asia/Shanghai"
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M